# create_timezone_csv_with_cities.ps1
# Exports Windows time zones to CSV and adds representative large cities.
# Generated by Copilot

param(
	[string]$OutputPath = (Join-Path -Path $PSScriptRoot -ChildPath "WindowsTimeZonesWithCities.csv")
)

$cityMap = @{
	"UTC" = @("London", "Accra", "Reykjavik")
	"GMT Standard Time" = @("London", "Dublin", "Lisbon")
	"W. Europe Standard Time" = @("Berlin", "Paris", "Madrid")
	"Central Europe Standard Time" = @("Budapest", "Prague", "Warsaw")
	"Romance Standard Time" = @("Paris", "Brussels", "Madrid")
	"Central European Standard Time" = @("Warsaw", "Belgrade", "Ljubljana")
	"E. Europe Standard Time" = @("Kyiv", "Sofia", "Bucharest")
	"FLE Standard Time" = @("Helsinki", "Riga", "Tallinn")
	"GTB Standard Time" = @("Athens", "Bucharest", "Istanbul")
	"Turkey Standard Time" = @("Istanbul", "Ankara", "Izmir")
	"Russian Standard Time" = @("Moscow", "Saint Petersburg", "Kazan")
	"South Africa Standard Time" = @("Johannesburg", "Cape Town", "Durban")
	"Egypt Standard Time" = @("Cairo", "Alexandria", "Giza")
	"Morocco Standard Time" = @("Casablanca", "Rabat", "Marrakesh")
	"Arabian Standard Time" = @("Dubai", "Abu Dhabi", "Muscat")
	"Arab Standard Time" = @("Riyadh", "Jeddah", "Mecca")
	"Middle East Standard Time" = @("Beirut", "Amman", "Damascus")
	"Israel Standard Time" = @("Jerusalem", "Tel Aviv", "Haifa")
	"Iran Standard Time" = @("Tehran", "Mashhad", "Isfahan")
	"India Standard Time" = @("Delhi", "Mumbai", "Bengaluru")
	"Pakistan Standard Time" = @("Karachi", "Lahore", "Islamabad")
	"Bangladesh Standard Time" = @("Dhaka", "Chittagong", "Khulna")
	"Sri Lanka Standard Time" = @("Colombo", "Kandy", "Galle")
	"Nepal Standard Time" = @("Kathmandu", "Pokhara", "Lalitpur")
	"SE Asia Standard Time" = @("Bangkok", "Jakarta", "Ho Chi Minh City")
	"Singapore Standard Time" = @("Singapore", "Kuala Lumpur", "Johor Bahru")
	"China Standard Time" = @("Shanghai", "Beijing", "Shenzhen")
	"Taipei Standard Time" = @("Taipei", "Kaohsiung", "Taichung")
	"Tokyo Standard Time" = @("Tokyo", "Osaka", "Nagoya")
	"Korea Standard Time" = @("Seoul", "Busan", "Incheon")
	"AUS Eastern Standard Time" = @("Sydney", "Melbourne", "Canberra")
	"Tasmania Standard Time" = @("Hobart", "Launceston", "Devonport")
	"AUS Central Standard Time" = @("Adelaide", "Darwin", "Alice Springs")
	"W. Australia Standard Time" = @("Perth", "Fremantle", "Bunbury")
	"New Zealand Standard Time" = @("Auckland", "Wellington", "Christchurch")
	"Central Pacific Standard Time" = @("Noumea", "Suva", "Honiara")
	"Hawaiian Standard Time" = @("Honolulu", "Hilo", "Kailua")
	"Alaskan Standard Time" = @("Anchorage", "Fairbanks", "Juneau")
	"Pacific Standard Time" = @("Los Angeles", "Vancouver", "Seattle")
	"Mountain Standard Time" = @("Denver", "Phoenix", "Calgary")
	"US Mountain Standard Time" = @("Phoenix", "Tucson", "Yuma")
	"Central Standard Time" = @("Chicago", "Dallas", "Houston")
	"Eastern Standard Time" = @("New York", "Toronto", "Boston")
	"Atlantic Standard Time" = @("Halifax", "Santo Domingo", "Bermuda")
	"SA Pacific Standard Time" = @("Bogota", "Lima", "Quito")
	"Pacific SA Standard Time" = @("Santiago", "Valparaiso", "Concepcion")
	"E. South America Standard Time" = @("Sao Paulo", "Rio de Janeiro", "Belo Horizonte")
	"Argentina Standard Time" = @("Buenos Aires", "Cordoba", "Rosario")
	"Greenland Standard Time" = @("Nuuk", "Sisimiut", "Ilulissat")
	"Azores Standard Time" = @("Ponta Delgada", "Angra do Heroismo", "Horta")
	"Cape Verde Standard Time" = @("Praia", "Mindelo", "Santa Maria")
}

$offsetFallbackMap = @{
	"-12:00:00" = @("Baker Island", "Howland Island")
	"-11:00:00" = @("Pago Pago", "Alofi")
	"-10:00:00" = @("Honolulu", "Papeete")
	"-09:30:00" = @("Marquesas")
	"-09:00:00" = @("Anchorage", "Juneau")
	"-08:00:00" = @("Los Angeles", "Vancouver")
	"-07:00:00" = @("Denver", "Phoenix")
	"-06:00:00" = @("Chicago", "Mexico City")
	"-05:00:00" = @("New York", "Toronto")
	"-04:00:00" = @("Santiago", "Caracas")
	"-03:30:00" = @("St. John's")
	"-03:00:00" = @("Sao Paulo", "Buenos Aires")
	"-02:00:00" = @("South Georgia")
	"-01:00:00" = @("Azores", "Cape Verde")
	"00:00:00"  = @("London", "Accra")
	"01:00:00"  = @("Berlin", "Paris")
	"02:00:00"  = @("Cairo", "Athens")
	"03:00:00"  = @("Moscow", "Riyadh")
	"03:30:00"  = @("Tehran")
	"04:00:00"  = @("Dubai", "Baku")
	"04:30:00"  = @("Kabul")
	"05:00:00"  = @("Karachi", "Tashkent")
	"05:30:00"  = @("Delhi", "Mumbai")
	"05:45:00"  = @("Kathmandu")
	"06:00:00"  = @("Dhaka", "Almaty")
	"06:30:00"  = @("Yangon")
	"07:00:00"  = @("Bangkok", "Jakarta")
	"08:00:00"  = @("Shanghai", "Singapore")
	"09:00:00"  = @("Tokyo", "Seoul")
	"09:30:00"  = @("Adelaide", "Darwin")
	"10:00:00"  = @("Sydney", "Melbourne")
	"11:00:00"  = @("Noumea", "Honiara")
	"12:00:00"  = @("Auckland", "Wellington")
	"12:45:00"  = @("Chatham Islands")
	"13:00:00"  = @("Nuku'alofa", "Apia")
	"14:00:00"  = @("Kiritimati")
}

function Get-CitiesFromDisplayName {
	param([string]$DisplayName)

	if (-not $DisplayName) {
		return @()
	}

	$clean = $DisplayName -replace "^\(UTC[^\)]*\)\s*", ""
	$parts = $clean -split "," | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" }
	$cities = @()

	foreach ($part in $parts) {
		$city = $part -replace "\b(and|the|of)\b", "" -replace "\s+", " "
		$city = $city.Trim(' ', '-', '/')
		if ($city -and $city.Length -ge 3) {
			$cities += $city
		}
	}

	return $cities | Select-Object -Unique
}

function Get-LargeCitiesForTimeZone {
	param(
		[string]$TimeZoneId,
		[string]$DisplayName,
		[TimeSpan]$BaseUtcOffset
	)

	if ($cityMap.ContainsKey($TimeZoneId)) {
		return ($cityMap[$TimeZoneId] -join "; ")
	}

	$displayCities = Get-CitiesFromDisplayName -DisplayName $DisplayName
	if ($displayCities.Count -gt 0) {
		return (($displayCities | Select-Object -First 3) -join "; ")
	}

	$offsetKey = $BaseUtcOffset.ToString()
	if ($offsetFallbackMap.ContainsKey($offsetKey)) {
		return ($offsetFallbackMap[$offsetKey] -join "; ")
	}

	return "N/A"
}

try {
	$timeZones = Get-TimeZone -ListAvailable | Sort-Object -Property Id | ForEach-Object {
		[PSCustomObject]@{
			Id                         = $_.Id
			DisplayName                = $_.DisplayName
			StandardName               = $_.StandardName
			DaylightName               = $_.DaylightName
			BaseUtcOffset              = $_.BaseUtcOffset
			SupportsDaylightSavingTime = $_.SupportsDaylightSavingTime
			LargeCities                = Get-LargeCitiesForTimeZone -TimeZoneId $_.Id -DisplayName $_.DisplayName -BaseUtcOffset $_.BaseUtcOffset
		}
	}

	$timeZones | Export-Csv -Path $OutputPath -NoTypeInformation -Encoding UTF8
	Write-Host "Timezone CSV with city names created: $OutputPath"
}
catch {
	Write-Error "Failed to generate timezone CSV with city names. $($_.Exception.Message)"
	exit 1
}
